version: '3'

services:
  keycloak:
    container_name: keycloak-demo
    image: quay.io/keycloak/keycloak:26.1.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    networks:
      - keycloak-spring-net
    command:
      - "start-dev"
    volumes:
      - keycloak_data:/opt/keycloak/data

networks:
  keycloak-spring-net:
    driver: bridge

volumes:
  keycloak_data: