spring:
  application:
    name: open-source-keycloak-lab

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/spring-demo

keycloak:
  client-id: springboot-app